language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
  global:
  matrix:
    - REQUIRE=no-dev

before_script:
  - composer self-update
  - composer --${REQUIRE} --prefer-source install

script: phpunit -c test/